python3 testing.py data/test/official_test_sets/subtask-1/En-Subtask1-test.tsv -l en -t 1 -m RGCN > ans_RGCN_en_t1.tsv
python3 testing.py data/test/official_test_sets/subtask-1/Fr-Subtask1-test.tsv -l fr -t 1 -m RGCN > ans_RGCN_fr_t1.tsv
python3 testing.py data/test/official_test_sets/subtask-1/It-Subtask1-test.tsv -l it -t 1 -m RGCN > ans_RGCN_it_t1.tsv
python3 testing.py data/test/official_test_sets/subtask-1/En-Subtask1-test.tsv -l en -t 1 -m GAT > ans_GAT_en_t1.tsv
python3 testing.py data/test/official_test_sets/subtask-1/Fr-Subtask1-test.tsv -l fr -t 1 -m GAT > ans_GAT_fr_t1.tsv
python3 testing.py data/test/official_test_sets/subtask-1/It-Subtask1-test.tsv -l it -t 1 -m GAT > ans_GAT_it_t1.tsv
python3 testing.py data/test/official_test_sets/subtask-1/En-Subtask1-test.tsv -l en -t 1 -m Parallel > ans_Par_en_t1.tsv
python3 testing.py data/test/official_test_sets/subtask-1/Fr-Subtask1-test.tsv -l fr -t 1 -m Parallel > ans_Par_fr_t1.tsv
python3 testing.py data/test/official_test_sets/subtask-1/It-Subtask1-test.tsv -l it -t 1 -m Parallel > ans_Par_it_t1.tsv
python3 testing.py data/test/official_test_sets/subtask-2/En-Subtask2-test.tsv -l en -t 2 -m RGCN > ans_RGCN_en_t2.tsv
python3 testing.py data/test/official_test_sets/subtask-2/Fr-Subtask2-test.tsv -l fr -t 2 -m RGCN > ans_RGCN_fr_t2.tsv
python3 testing.py data/test/official_test_sets/subtask-2/It-Subtask2-test.tsv -l it -t 2 -m RGCN > ans_RGCN_it_t2.tsv
python3 testing.py data/test/official_test_sets/subtask-2/En-Subtask2-test.tsv -l en -t 2 -m GAT > ans_GAT_en_t2.tsv
python3 testing.py data/test/official_test_sets/subtask-2/Fr-Subtask2-test.tsv -l fr -t 2 -m GAT > ans_GAT_fr_t2.tsv
python3 testing.py data/test/official_test_sets/subtask-2/It-Subtask2-test.tsv -l it -t 2 -m GAT > ans_GAT_it_t2.tsv
python3 testing.py data/test/official_test_sets/subtask-2/En-Subtask2-test.tsv -l en -t 2 -m Parallel > ans_Par_en_t2.tsv
python3 testing.py data/test/official_test_sets/subtask-2/Fr-Subtask2-test.tsv -l fr -t 2 -m Parallel > ans_Par_fr_t2.tsv
python3 testing.py data/test/official_test_sets/subtask-2/It-Subtask2-test.tsv -l it -t 2 -m Parallel > ans_Par_it_t2.tsv
