#python3 training.py data/train/train_subtask-1/ -l en -t 1 -m GAT > log_GAT_en_t1.txt
#python3 training.py data/train/train_subtask-1/ -l en -t 1 -m RGCN > log_RGCN_en_t1.txt
#python3 training.py data/train/train_subtask-1/ -l en -t 1 -m Parallel > log_Parallel_en_t1.txt
python3 training.py data/train/train_subtask-1/ -l it -t 1 -m GAT > log_GAT_it_t1.txt
python3 training.py data/train/train_subtask-1/ -l it -t 1 -m RGCN > log_RGCN_it_t1.txt
python3 training.py data/train/train_subtask-1/ -l it -t 1 -m Parallel > log_Parallel_it_t1.txt
python3 training.py data/train/train_subtask-1/ -l fr -t 1 -m GAT > log_GAT_fr_t1.txt
python3 training.py data/train/train_subtask-1/ -l fr -t 1 -m RGCN > log_RGCN_fr_t1.txt
python3 training.py data/train/train_subtask-1/ -l fr -t 1 -m Parallel > log_Parallel_fr_t1.txt
python3 training.py data/train/train_subtask-2/ -l en -t 2 -m GAT > log_GAT_en_t2.txt
python3 training.py data/train/train_subtask-2/ -l en -t 2 -m RGCN > log_RGCN_en_t2.txt
python3 training.py data/train/train_subtask-2/ -l en -t 2 -m Parallel > log_Parallel_en_t2.txt
python3 training.py data/train/train_subtask-2/ -l it -t 2 -m GAT > log_GAT_it_t2.txt
python3 training.py data/train/train_subtask-2/ -l it -t 2 -m RGCN > log_RGCN_it_t2.txt
python3 training.py data/train/train_subtask-2/ -l it -t 2 -m Parallel > log_Parallel_it_t2.txt
python3 training.py data/train/train_subtask-2/ -l fr -t 2 -m GAT > log_GAT_fr_t2.txt
python3 training.py data/train/train_subtask-2/ -l fr -t 2 -m RGCN > log_RGCN_fr_t2.txt
python3 training.py data/train/train_subtask-2/ -l fr -t 2 -m Parallel > log_Parallel_fr_t2.txt
